### ISSUE TITLE
다음에디터로 작성한 글 보기가 안되요. (모바일)

### ISSUE THREAD

**Issue by amzang** [kakao/DaumEditor#500]
안녕하세요.
이곳과 웹검색을 통해서 문제를 해결하려고 했으나, 해결할 길이 없어서 이렇게 글을 올립니다.
홈페이지에 다음에디터를 붙여서 사용중이구요.
다음에디터로 작성하여, 저희 서버의 DB 에 저장하고, 게시물 내용을보여주는 형태입니다.
게시물 내용 보여주기 할때에, DB에 저장되어있는 내용을 그대로 보여주면, 웹에서는 문제가 되질 않도록 해놓았습니다.

그런데, 모바일에서 보게되면, 저장된 이미지의 사이즈가 fix되어서, 화면이 커져, 가로스크롤이 생깁니다.
물론, 웹에서 글 작성시, 처음부터, 이미지를 아주 작은 사이즈로 저장하면, 모바일에서 가로스크롤이 들 생기죠.

한번 저장으로 모바일과 웹 모두에서 이상없이 보고싶은데,
해결방법이 없을까요?

**Comment by easylogic** [comment]
@media 나 기타 모바일 체크 로직 을 써서  

```css
img { max-width:100% !important } 
```
로 맞추시면  모바일 화면에 맞게 보이실 것 같아요.

**Comment by amzang** [comment]
<style>
@media (max-width: 768px) and (min-width: 320px){
		.img{max-width:100% !important}
		}
</style>

이렇게 쓰라고 말씀하시는 건가요?
전 엔지니어라 잘 모르겠는데요. 디자이너분이 안된다고 하던데요.
넘어오는 값에 px값이 있어서, 이미지를 작게할 수 없다고 합니다.

혹시 제가 잘 못 이해했을까요?

**Comment by easylogic** [comment]
```css
@media (max-width: 768px) and (min-width: 320px){ 
     img{
       width: 100% !important;
       max-width:100% !important;
     }
}
```

그럼 이렇게 한번 해보시죠. width 도 같이 늘려주는 방식으로 하시면 될 듯 합니다.
